# Generated by Django 5.0 on 2024-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerctrl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('WEB', 'Web Server'), ('DNS', 'Dns Server'), ('DHCP', 'Dhcp Server')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
