# Generated by Django 5.0.1 on 2024-01-15 23:58

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockerctrl', '0004_network_port_network_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network',
            field=netfields.fields.CidrAddressField(max_length=43),
        ),
    ]
