# Generated by Django 5.0.1 on 2024-01-16 08:24

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockerctrl', '0005_alter_network_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='gateway',
            field=netfields.fields.InetAddressField(default='192.168.100.1', max_length=39),
            preserve_default=False,
        ),
    ]
