# Generated by Django 5.0.1 on 2024-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerctrl', '0006_network_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='x',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='y',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('WEB', 'Web Server'), ('DNS', 'Dns Server'), ('SMTP', 'Smtp Server')], max_length=50),
        ),
    ]
