# Generated by Django 5.0.1 on 2024-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerctrl', '0007_machine_x_machine_y_alter_machine_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='x',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='y',
            field=models.BigIntegerField(default=0),
        ),
    ]
