# Generated by Django 5.0.1 on 2024-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerctrl', '0009_machine_confdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='pt_container_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
